sudo: false
dist: focal
addons:
  apt:
    packages:
      - check
      - libcppunit-dev
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy2.7-7.3.1"
  - "pypy3.6-7.3.1"
matrix:
  include:
    - dist: xenial
      python: pypy3.5-7.0.0
install:
 - pip install -U pip
 - pip install -U wheel setuptools
 - pip install -U .[test,docs]
 - pip list
 - python --version
 - autoreconf -fi && ./configure && make
script:
 - make check
 - make distcheck
 - rst2html.py README.rst README.html
